- hosts: tomcat
  connection: local
  become: true
  become_user: root
  gather_facts: false
  vars:
  - warName: java-example.war
  - warDestPath: /etc/tomcat9/webapps
  tasks:
    - name: stop tomcat
      shell: /etc/tomcat9/bin/shutdown.sh
    - name: maven clean package
      command: mvn -f /var/lib/jenkins/workspace/ansible-jenkins-tomcat-deployment/pom.xml clean package
    - name: delete existing war directories in tomcat webapps
      file: path=/etc/tomcat9/webapps/java-example.war state=absent
    - name: delete existing war file in tomcat webapps
      file: path=/usr/share/tomcat/webapps/myproject state=absent
    - name: copy war file to the tomcat webapp directory
      copy: src=/var/lib/jenkins/workspace/ansible-jenkins-tomcat-deployment/target/{{ warName }} dest={{ warDestPath }}/{{ warName }}
    - name: start tomcat
      shell: /etc/tomcat9/bin/startup.sh

